### ISSUE TITLE
Scrap Trello Jobs

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/career-craft-scrapper#10]
Link --> https://trello.com/jobs

Please comment down below if you want to work on this

Please ping me if you need any help or clarification

**Comment by bhima2001** [comment]
I would like to work on this. Please elaborate further about the requirement.

**Comment by dotslashbit** [comment]
@bhima2001 sure go ahead I'll assign this to you

**Comment by dotslashbit** [comment]
@bhima2001 we are using pupeteer to scrap jobs from career pages, you just need to scrap and check if the console.table shows the scrapped data perfectly or not.

I hope this clarifies everything. If not then please ping me

**Comment by bhima2001** [comment]
[f82f7b1](https://github.com/The-Enthusiast-404/career-craft-scrapper/pull/31/commits/f82f7b1c1419b5b834fc9ec961a971044508adcf)

**Comment by bhima2001** [comment]
https://github.com/The-Enthusiast-404/career-craft-scrapper/pull/31
