### ISSUE TITLE
Scrap Toptal Jobs

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/career-craft-scrapper#17]
Link --> https://www.toptal.com/careers

Please comment down below if you want to work on this

Please ping me if you need any help or clarification

**Comment by Goutamchoudhary907** [comment]
Hey @dotslashbit i want to work on this please assign me this

**Comment by dotslashbit** [comment]
@Goutamchoudhary907 go for it

**Comment by dotslashbit** [comment]
@Goutamchoudhary907 Just take the first occurence of experience as most likely that's the highest priority anyway

**Comment by Goutamchoudhary907** [comment]
Ok
