### ISSUE TITLE
Scrap CircleCI Jobs

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/career-craft-scrapper#21]
Link --> https://circleci.com/careers/

Please comment down below if you want to work on this

Please ping me if you need any help or clarification

**Comment by Goutamchoudhary907** [comment]
I want to work on this , plz assign this to me

**Comment by dotslashbit** [comment]
@Goutamchoudhary907 sure go ahead

**Comment by Goutamchoudhary907** [comment]
Thanks for assigning , I am new to open source can be plz guide me how to start

**Comment by dotslashbit** [comment]
@Goutamchoudhary907  sure I can help you, let's discuss on twitter, just DM me there. Explaining everything here will clutter the issue page

**Comment by Goutamchoudhary907** [comment]
Just messaged you, please check
