### ISSUE TITLE
Scrap Segment Jobs

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/career-craft-scrapper#23]
Link --> https://segment.com/jobs/

Please comment down below if you want to work on this

Please ping me if you need any help or clarification

**Comment by ilumin** [comment]
Assign me, please

**Comment by dotslashbit** [comment]
Done

**Comment by ilumin** [comment]
Segment render their jobs from JSON (`https://www.twilio.com/en-us/company/jobs/jcr:content/root/global-main/section/column_control/column-0/jobs_component.jobs.json`). Should we just directly get from JSON instead of using Puppeteer?

**Comment by dotslashbit** [comment]
Yeah let's do that,just make sure the formatting stays the same
