### ISSUE TITLE
Scrap Netflix Jobs

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/career-craft-scrapper#27]
Link --> https://jobs.netflix.com/

Please comment down below if you want to work on this

Please ping me if you need any help or clarification

**Comment by munnavuyyuru** [comment]
@dotslashbit ,assign me

**Comment by dotslashbit** [comment]
@munnavuyyuru here you go

**Comment by mohdshubair313** [comment]
assign me please
