### ISSUE TITLE
Scrap Jobs from Gitlab

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/career-craft-scrapper#4]
Page link --> https://about.gitlab.com/jobs/

**Comment by Jambong-Ralpher** [comment]
hi @dotslashbit ,I am interested to work on this. need clarification how

**Comment by dotslashbit** [comment]
@Jambong-Ralpher sure go ahead, we are using pupeteer library to scrap data. It's a js library, pretty simple to learn. Let me know if you have any doubts on how to start or anything, don't hesitate

**Comment by Jambong-Ralpher** [comment]
@dotslashbit  please umm Given the efficiency and reliability of the GitLab API, I suggest replacing the Puppeteer-based scraping implementation for GitLab jobs with a direct API approach.   just a suggestion.

**Comment by dotslashbit** [comment]
@Jambong-Ralpher yeah we can do that but you still need to keep the output format as I want to put the data in our db

**Comment by Jambong-Ralpher** [comment]
hi @dotslashbit  i have opened a pull request

**Comment by Jambong-Ralpher** [comment]
<img width="562" alt="gitlab" src="https://github.com/user-attachments/assets/42ac06d5-1175-4b18-a2c3-d5ab7ef7bbe2">
